name: Releast


on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Install musl
        run: rustup target add x86_64-unknown-linux-musl
      
      - name: Install 2
        run: sudo apt-get update
      
      - name: Install 3
        run: sudo apt-get install musl-tools -y

      - name: Install 4
        run: sudo apt-get -y install pkg-config libssl-dev

      - name: Build
        run: cargo build --all --release --target=x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/cubox-image
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}